### ISSUE TITLE
Add hot reloading

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/whatgotdone#67]
# Gin

Gets a nil pointer dereference:

```
PS C:\Projects\whatgotdone> C:\Users\Mike\go\bin\gin.exe --godep run web/main.go
[gin] Listening on port 3000
[gin] Building...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x69cce8]

goroutine 1 [running]:
syscall.WaitStatus.ExitStatus(...)
        C:/Go/src/syscall/syscall_windows.go:846
os.(*ProcessState).success(...)
        C:/Go/src/os/exec_posix.go:74
os.(*ProcessState).Success(...)
        C:/Go/src/os/exec.go:152
github.com/codegangsta/gin/lib.(*builder).Build(0xc00001a300, 0xc0000733a0, 0x1)
        C:/Users/Mike/go/pkg/mod/github.com/codegangsta/gin@v0.0.0-20171026143024-cafe2ce98974/lib/builder.go:62 +0x328
main.build(0x825500, 0xc00001a300, 0x825dc0, 0xc00001a360, 0xc000084190)
        C:/Users/Mike/go/pkg/mod/github.com/codegangsta/gin@v0.0.0-20171026143024-cafe2ce98974/main.go:234 +0xbc
main.MainAction(0xc0000b86e0)
        C:/Users/Mike/go/pkg/mod/github.com/codegangsta/gin@v0.0.0-20171026143024-cafe2ce98974/main.go:203 +0xa4c
gopkg.in/urfave/cli%2ev1.HandleAction(0x740920, 0x7dd3f8, 0xc0000b86e0, 0xc00001a200, 0x0)
        C:/Users/Mike/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:492 +0x83
gopkg.in/urfave/cli%2ev1.Command.Run(0x7c42b7, 0x3, 0x7c3f73, 0x1, 0x0, 0x0, 0x0, 0x7d52b9, 0x32, 0x0, ...)
        C:/Users/Mike/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/command.go:210 +0x9a9
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00008a820, 0xc000042100, 0x4, 0x4, 0x0, 0x0)
        C:/Users/Mike/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:255 +0x68e
main.main()
        C:/Users/Mike/go/pkg/mod/github.com/codegangsta/gin@v0.0.0-20171026143024-cafe2ce98974/main.go:140 +0xd1f
```

# realize

Insists on build or install rather than `go run` but I can't figure out which command it's actually running to do the build/install.

# air

Doesn't seem to pick up on file changes.

**Comment by mtlynch** [comment]
Fixed by integrating modd
